# Generated by Django 5.2.12 on 2026-03-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ticket_status'),
        ('core', '0013_seed_pool_inventory_data'),
    ]

    operations = [
    ]
