# Generated by Django 5.2.12 on 2026-03-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ticket_status_in_progress'),
        ('core', '0015_user_role_manager'),
    ]

    operations = [
    ]
