# Generated by Django 5.2.12 on 2026-03-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20260320_0213'),
        ('core', '0016_user_invite'),
    ]

    operations = [
    ]
