# Generated by Django 5.2.12 on 2026-04-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetScanEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("check_out", "Check Out"),
                            ("check_in", "Check In"),
                            ("report_fault", "Report Fault"),
                            ("update_condition", "Update Condition"),
                        ],
                        max_length=40,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True, default="")),
                ("previous_condition", models.CharField(blank=True, default="", max_length=60)),
                ("new_condition", models.CharField(blank=True, default="", max_length=60)),
                ("previous_status", models.CharField(blank=True, default="", max_length=60)),
                ("new_status", models.CharField(blank=True, default="", max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_scan_actions",
                        to="core.user",
                    ),
                ),
                (
                    "consumable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scan_events", to="core.consumable"
                    ),
                ),
                (
                    "linked_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_scan_events",
                        to="core.ticket",
                    ),
                ),
                (
                    "target_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_scan_targets",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "asset_scan_events",
            },
        ),
    ]
